package com.example.lifediary.ui.common

object UiConstants {
	object WomanSection {
		const val DEFAULT_DURATION_OF_MENSTRUAL_CYCLE = 28
		const val MIN_DURATION_OF_MENSTRUAL_CYCLE = 15
		const val MAX_DURATION_OF_MENSTRUAL_CYCLE = 50
		const val DEFAULT_DURATION_OF_MENSTRUATION_PERIOD = 5
		const val MIN_DURATION_OF_MENSTRUATION_PERIOD = 1
		const val MAX_DURATION_OF_MENSTRUATION_PERIOD = 10
		const val DEFAULT_MONTH_NUMBER_IN_PAST_TO_DISPLAY_IN_CALENDAR = 15L
		const val DEFAULT_MONTH_NUMBER_IN_FUTURE_TO_DISPLAY_IN_CALENDAR = 15L
	}
}